config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
      resources :general_shopping_list, only: [:index]
    end
  end

  resources :public_recipes, only: [:index]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, length: { in: 1..18 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { in: 1..450 }

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  def total_price
    foods.sum('price  * recipe_foods.quantity')
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy]
  before_action :set_user, only: %i[index show create]

  # GET /recipes or /recipes.json
  def index
    @recipes = @user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_foods = @recipe.recipe_foods.includes(:food, :recipe).order(:id)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(user: current_user, **recipe_params)

    if @recipe.save
      redirect_to user_recipes_url, notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
    redirect_to user_recipes_url
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    redirect_to user_recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_recipe
    @recipe = set_user.recipes.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/_form.html.erb
<%= form_with model: recipe, url: user_recipes_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group input-group-outline mb-3">
    <label class="form-label">Name</label>
    <%= form.text_field :name, class: 'form-control focus:border-blue-600' %>
  </div>

  <div class="input-group input-group-outline mb-3">
    <label class="form-label">Preparation Time</label>
    <%= form.text_field :preparation_time, class: 'form-control focus:border-blue-600' %>
  </div>

  <div class="input-group input-group-outline mb-3">
    <label class="form-label">Cooking Time</label>
    <%= form.number_field :cooking_time, class: 'form-control focus:border-blue-600' %>
  </div>

  <div class="input-group input-group-outline mb-6 bg-green-50">
    <label class="form-label">Description</label>
    <%= form.text_area :description, class: "form-control", rows: "7" %>
  </div>

  <label class="self-start mt-3 inline-flex items-center">
    <%= form.check_box :public, class: 'checkbox absolute z-10 cursor-pointer opacity-0 accent-green-500' %>
    <div class="form-check-input"></div>
    <span class="text-gray-700 cursor-pointer select-none">Public</span>
  </label>

  <%= form.button "Create Recipe", type: "submit", class: "button mb-5 button-green bg-green-300", 'data-ripple-light': true %>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="card mb-5">
  <div class="card-body flex">
    <div class="flex flex-col justify-items-center gap-8 basis-1/3">
      <%= link_to user_recipe_path(recipe.user, recipe), class: 'group/recipe text-slate-500 font-bold flex items-center p-1.5 rounded-[12px] hover:bg-slate-200 w-max' do %>
        <%= recipe.name %>
        <span class="mx-2">
          <svg class="h-4 w-4 invisible group-hover/recipe:visible group-hover/recipe:translate-x-1.5 group-hover/recipe:text-slate-500 transition duration-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
          </svg>
        </span>
      <% end %>
      <% if can? :destroy, recipe %>
        <%= button_to user_recipe_path(recipe.user,recipe), method: :delete, class: 'self-start group mb-4 flex items-center gap-2 button button-red bg-red-500 w-max' do %>
          <span class="whitespace-nowrap"><%= 'Remove' %> </span>
          <svg class="w-6 h-6 group-hover:animate-wiggle" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        <% end %>
      <% end %> 
    </div>
    <p class="mb-3 basis-2/3">
      <%= recipe.description %>
    </p>
  </div>
    <p class="ml-5 mb-2 text-white text-sm w-max font-bold p-1 rounded-md <%= recipe.public ? 'bg-green-600' : 'bg-slate-500' %>">
      <%= recipe.public ? 'Recipe is Public' : 'Recipe is Private'%>
    </p>
</div>

app/views/recipes/_recipe_detail.html.erb
<h1 class="text-center text-2xl font-bold underline decoration-purple-500 underline-offset-4"> <%= recipe.name %></h1>
<div class="w-10/12 mx-auto mb-4 flex justify-between">
  <div class ="flex flex-col">
    <h2 class="text-xl font-semibold mb-4">Preparation Time: <%= recipe.preparation_time %></h2>
    <h2 class=" text-xl font-semibold mb-4">Cooking Time: <%= recipe.cooking_time %></h2>
    <p><%= recipe.description %></p>
  </div>

  <label class="mt-3 inline-flex items-center">
    <input
      type="checkbox"
      class="checkbox absolute z-10 cursor-pointer opacity-0"
      <% if recipe.public %>
      checked='checked'
      <% end %>
    />
    <div class="form-check-input"></div>
    <span class="text-gray-700 cursor-pointer select-none">Public</span>
</label>
</div>

app/views/recipes/index.html.erb
<h1 class="text-2xl text-center mb-3">Recipes List</h1>

<div id="recipes" class="flex flex-col w-[40%] mx-auto">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>

  <%= link_to new_user_recipe_path, class: "my-4 flex items-center gap-2 button button-green bg-green-300 w-max" do %>
    <span class="whitespace-nowrap"><%= 'New Recipe' %> </span>
    <svg class="w-8 h-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
    </svg>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1 class="text-2xl text-center mb-3">New recipe</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<% if can? :manage, @recipe or @recipe.public %>
  <%= render "recipe_detail", recipe: @recipe %>
  <div class="flex flex-col mx-auto w-11/12">
    <% if can? :manage, @recipe %>
      <div class="flex gap-10 mb-5">
      <%= link_to user_recipe_general_shopping_list_index_path(@user, @recipe), class: 'flex items-center gap-2 button button-dark bg-purple-500 w-max', 'data-ripple-light': true do %>
        <span class="whitespace-nowrap"><%= 'Generate List' %> </span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zM3.75 12h.007v.008H3.75V12zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm-.375 5.25h.007v.008H3.75v-.008zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
        </svg>
      <% end %>
      <%= link_to new_user_recipe_recipe_food_path(@user, @recipe), class: 'flex items-center gap-2 button button-green bg-emerald-500 w-max', 'data-ripple-light': true do %>
        <span class="whitespace-nowrap"><%= 'Add ingredient' %> </span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      <% end %>
      </div>
    <% end %>
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full">
            <thead class="bg-gray-800 border-b">
              <tr class="">
                <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                  Food
                </th>
                <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                  Quantity
                </th>
                <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                  Value
                </th>
                <th colspan="2" class="text-sm text-center font-medium text-white px-6 py-4 text-left">
                Actions
                </th>
              </tr>
            </thead>
            <tbody>
              <%@recipe_foods.each do |recipe_food| %>
                <tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    <%= recipe_food.food.name %>
                  </td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    <%= recipe_food.quantity %>
                  </td>
                  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    <%= recipe_food.quantity * recipe_food.food.price %>
                  </td>
                  <% if can? :manage, recipe_food.recipe %>
                  <td class="text-sm text-center text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    <%= link_to "Modify", edit_user_recipe_recipe_food_path(@user, @recipe, recipe_food), class: 'hover:bg-amber-400 hover:text-white button capitalize p-1' %>
                  </td>
                  <td class="text-sm text-center text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    <%= button_to "Remove", user_recipe_recipe_food_path(@user, @recipe, recipe_food), method: :delete, class: 'hover:bg-red-400 hover:text-white button capitalize p-1' %>
                  </td>
                  <% end %>
                  <% if cannot? :manage , @recipe %>
                  <td class="text-sm text-center text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                    <span class="hover:bg-purple-400 hover:text-white button capitalize p-1">No actions for you here</span>
                    </td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% if can? :destroy, @recipe %>
    <div>
      <%= button_to user_recipe_path(@user,@recipe), method: :delete, class: 'group mb-4 flex items-center gap-2 button button-red bg-red-500 w-max' do %>
        <span class="whitespace-nowrap"><%= 'Destroy this recipe' %> </span>
        <svg class="w-6 h-6 group-hover:animate-wiggle" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
        </svg>
      <% end %>
    </div>
    <% end %>  
  </div>
<% else %>
  <p>Sorry, you don't have access to this recipe</p>
<% end %> 