config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
      resources :general_shopping_list, only: [:index]
    end
  end

  resources :public_recipes, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { in: 2..20 }

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all.order(:id)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/users/_user.html.erb
<%= link_to user_path(user) do %>
  <li class="user mt-4 flex items-center gap-10">
    <div class="user-info w-10/12 border border-red flex justify-between p-4 items-center">
      <h3 class="username text-2xl ml-2"><%= user.name %></h3>
      <div class="flex flex-col self-end">
        <span class="mr-2">Number of Foods: <%= user.foods.count %></span>
        <span class="mr-2">Number of Recipes: <%= user.recipes.count %></span>
      </div>
    </div>
  </li>
<% end %>

app/views/users/index.html.erb
<% content_for :title, "Recipe App" %>
<section class="users-container flex flex-col justify-center w-8/12 mx-auto">
  <% @users.each do |user| %>
    <%= render "user", user: user %>
  <% end %>
</section>

app/views/users/show.html.erb
<section class="users-container w-6/12 mx-auto">
  <%= render "user", user: @user %>
  <div class="food-recipe-actions flex gap-3 justify-center">
    <%= link_to user_foods_path(@user), class: 'self-center' do %>
      <button type="button" class="see-all-posts mt-4 button text-white bg-gradient-to-r from-blue-500 to-blue-200 hover:shadow-none shadow-none border-2 hover:border-blue-400 hover:text-blue-400 hover:from-white hover:to-white">See all Foods</button>
    <% end %>
    <%= link_to user_recipes_path(@user) do %>
      <button type="button" class="create-post mt-4 button text-white bg-gradient-to-r from-green-500 to-green-200 hover:shadow-none shadow-none border-2 hover:border-green-400 hover:text-green-400 hover:from-white hover:to-white">See all Recipes</button>
    <% end %>
  </div>
</section>