config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
      resources :general_shopping_list, only: [:index]
    end
  end

  resources :public_recipes, only: [:index]
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true, length: { in: 1..15 }
  validates :measurement_unit, presence: true, length: { in: 1..9 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]
  before_action :set_user, only: %i[index show create]

  def index
    @foods = @user.foods
  end

  def show
    @food
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(**food_params)

    if @food.save
      redirect_to user_foods_url, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @food.destroy
      flash[:success] = 'Food was successfully deleted.'
    else
      flash[:error] = 'Error: Food could not be deleted'
    end
    redirect_to user_foods_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_food
    @food = set_user.foods.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:user_id, :name, :measurement_unit, :price, :quantity)
  end
end

app/views/foods/_food.html.erb
<tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
  <td class="group/food flex items-center cursor-pointer text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
    <%= food.name %>
    <%= link_to user_food_path(@user, food), class: 'group/open text-slate-500 font-bold invisible flex items-center p-1.5 rounded-[12px] hover:bg-slate-200 ml-8 group-hover/food:visible' do %>
      <%= 'Open' %>
      <span class="ml-2">
        <svg class="h-4 w-4 group-hover/open:translate-x-0.5 group-hover/open:text-slate-500 transition duration-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
        </svg>
      </span>
    <% end %>
  </td>
  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
    <%= food.measurement_unit %>
  </td>
  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
    <%= food.price %>
  </td>
  <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
    <%= food.quantity %>
  </td>
  <% if can? :destroy, food %>
  <td class="text-sm text-center text-gray-900 font-light px-6 py-4 whitespace-nowrap">
    <%= button_to "Remove", user_food_path(@user, food), method: :delete , class: 'hover:bg-red-400 hover:text-white button capitalize p-1' %>
  </td>
  <% end %>
  <% if cannot? :destroy, food %>
  <td class="text-sm text-center text-gray-900 font-light px-6 py-4 whitespace-nowrap">
    <span class="hover:bg-purple-400 hover:text-white button capitalize p-1">No actions for you here</span>
  </td>
  <% end %>
</tr>

app/views/foods/_form.html.erb
<%= form_with model: food, url: user_foods_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group input-group-outline mb-3">
    <label class="form-label">Name</label>
    <%= form.text_field :name, class: 'form-control focus:border-blue-600' %>
  </div>

  <div class="input-group input-group-outline mb-3">
    <label class="form-label">Measurement Unit</label>
    <%= form.text_field :measurement_unit, class: 'form-control focus:border-blue-600' %>
  </div>

  <div class="input-group input-group-outline mb-3">
    <label class="form-label">Unit Price</label>
    <%= form.number_field :price, class: 'form-control focus:border-blue-600' %>
  </div>

  <div class="input-group input-group-outline mb-4">
    <label class="form-label">Quantity</label>
    <%= form.number_field :quantity, class: 'form-control focus:border-blue-600' %>
  </div>

  <%= form.button "Create Food", type: "submit", class: "button button-blue bg-blue-300", 'data-ripple-light': true %>

<% end %>

app/views/foods/index.html.erb
<h1 class="text-2xl text-center mb-3">Food List</h1>

<div class="flex flex-col mx-auto w-10/12">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-gray-800 border-b">
            <tr class="">
              <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                Food
              </th>
              <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                Measurement Unit
              </th>
              <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                Unit_Price
              </th>
              <th scope="col" class="text-sm font-medium text-white px-6 py-4 text-left">
                Quantity
              </th>
              <th scope="col" class="text-sm text-center font-medium text-white px-6 py-4 text-left">
               Action
              </th>
            </tr>
          </thead>
          <tbody>
            <%@foods.each do |food| %>
              <%= render food %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%= link_to new_user_food_path, class: "mb-4 flex items-center gap-2 button button-blue bg-blue-300 w-max" do %>
    <span class="whitespace-nowrap"><%= 'New food' %> </span>
    <svg class="w-8 h-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
    </svg>
  <% end %>
</div>

app/views/foods/new.html.erb
<h1 class="text-2xl text-center mb-3">Add New food</h1>

<%= render "form", food: @food %>

<br />

app/views/foods/show.html.erb
<div class="w-[30rem] border-2 border-b-4 border-gray-200 rounded-xl hover:bg-gray-100 mx-auto">
  <div class="grid grid-cols-6 p-5 gap-y-2">

    <!-- Food Picture -->
    <div>
      <img src="https://upload.wikimedia.org/wikipedia/commons/a/a6/Foods_-_Idil_Keysan_-_Wikimedia_Giphy_stickers_2019.gif" class="max-w-20 max-h-20 rounded-full" />
    </div>

    <!-- Description -->
    <div class="col-span-5 md:col-span-4 ml-4">
      <p class="text-sky-500 font-bold text-lg"> <%= @food.name %> </p>
      <p class="text-gray-600 font-bold"> [Measurement Unit] <%= @food.measurement_unit.capitalize %> </p>
      <p class="text-gray-400 underline underline-offset-4 decoration-amber-600"> Quantity in store: 
      <span class="text-sky-500 font-semibold"><%= @food.quantity %></span> </p>
    </div>

    <!-- Price -->
    <div class="flex col-start-2 ml-4 md:col-start-auto md:ml-0 md:justify-end">
      <p class="rounded-lg text-sky-500 font-bold bg-sky-100  py-1 px-3 text-sm w-fit h-fit"> 
        $ <%= @food.price %>
      </p>
    </div>
  </div>
</div>