config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  resources :users, only: [:index, :show] do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do
      resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
      resources :general_shopping_list, only: [:index]
    end
  end

  resources :public_recipes, only: [:index]
end

app/views/layouts/_bottom_header.html.erb
<!-- Ripple effect -->
<%= javascript_include_tag 'https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js', defer: true %>  
<!-- Material Input -->
<%# javascript_include_tag 'https://unpkg.com/@material-tailwind/html@latest/scripts/input.js', defer: true %> 
<!-- Material Menu PopOver -->
<%= javascript_include_tag 'https://unpkg.com/@material-tailwind/html@latest/scripts/popover.js', defer: true %>
<!-- Material Switch -->
<%# javascript_include_tag 'https://unpkg.com/@material-tailwind/html@latest/scripts/toggle.js', defer: true %>

app/views/layouts/_footer.html.erb
<footer class="fixed bottom-0 left-0 right-0 bg-darkSlate text-gray-100">
  <p class="flex items-center justify-center font-bold">
  Made with 
  <%= image_tag 'footer-cookies.png', class: 'w-12' %>
  by
  <%= link_to 'https://github.com/michael-duke', class: "mx-1 underline decoration-cyan-800"  do %>
    Michael
  <% end %>
  and
   <%= link_to 'https://github.com/samiullah997', class: "ml-1 underline decoration-purple-500"  do %>
    Samiullah
   <% end %>
  </p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="sticky z-50 top-0 w-full flex justify-start flex-wrap items-center gap-10 py-4 bg-gray-100 text-gray-500 shadow-lg navbar navbar-expand-lg navbar-light">
  <%= link_to users_path, class: 'mr-8 flex items-center gap-2' do %>
    <%= image_tag "recipe-logo.webp", class: 'h-24 w-24 object-cover rounded-full ring-2 ring-purple-500' %>
    <span class="text-xl uppercase tracking-[.25em]">Recipe App</span>
  <% end %>
  
  <%= link_to 'javascript:history.back()', class: 'uppercase flex gap-1 tracking-widest font-semibold' do %>
    <span class="whitespace-nowrap"><%= 'back' %> </span>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M21 16.811c0 .864-.933 1.405-1.683.977l-7.108-4.062a1.125 1.125 0 010-1.953l7.108-4.062A1.125 1.125 0 0121 8.688v8.123zM11.25 16.811c0 .864-.933 1.405-1.683.977l-7.108-4.062a1.125 1.125 0 010-1.953L9.567 7.71a1.125 1.125 0 011.683.977v8.123z" />
    </svg>
  <% end %>  
  
  <% if current_user %>
    <%= link_to user_foods_url(current_user), class: "tracking-widest uppercase text-base font-semibold" do %>
      <span class="whitespace-nowrap"><%= 'Foods' %> </span>
    <% end %>
    <%= link_to user_recipes_url(current_user), class: "tracking-widest uppercase text-base font-semibold" do %>
      <span class="whitespace-nowrap"><%= 'Recipes' %> </span>
    <% end %>
  <% end %>

  <%= link_to public_recipes_url, class: "tracking-widest uppercase text-base font-semibold" do %>
    <span class="whitespace-nowrap"><%= 'Public Recipes' %> </span>
  <% end %>
  
  <div class="ml-auto">
    <button
      class="<%= current_user ? 'button button-cyan' : 'border bg-amber-500 w-max text-gray-100 p-2 hover:text-amber-500 hover:bg-transparent' %>"
      data-ripple-light="true"
      data-popover-target="menu"
    >
      <% if current_user %>
        Hello, <%= current_user.name %>
      <% elsif controller_name != 'sessions' and controller_name != 'registrations' %>
        Hi, Guest User
      <% else %>
        Menu
      <% end %>
    </button>
    <ul role="menu" data-popover="menu" data-popover-placement="bottom" class="p-2">
      <li role="menuitem" class="mb-2">
        <div class="menu-item" href="#">
          <% if current_user %>
            <div class="flex items-center py-1">
              <%= button_to destroy_user_session_path, method: :delete, class: 'mr-8 flex items-center gap-2' do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15M12 9l-3 3m0 0l3 3m-3-3h12.75" />
                </svg>
                <span class="my-auto ml-2 normal-case">Log Out</span>
              <% end %>
            </div>
          <% else %>
            <div class="flex items-center py-1">
              <%= link_to users_path, class: 'mr-8 flex items-center gap-2' do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                <span class="my-auto ml-2 normal-case">Guest User</span>
              <% end %>
            </div>
          <% end %>
        </div>
      </li>
      <% unless current_user %>
        <li role="menuitem" class="mb-2">
          <div class="menu-item">
            <div class="flex items-center py-1">
              <%= link_to new_user_session_path, class: 'mr-8 flex items-center gap-2' do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
                </svg>
                <span class="my-auto ml-2 normal-case">Log In</span>
              <% end %>
            </div>
          </div>
        </li>
        <li role="menuitem">
          <div class="menu-item">
            <div class="flex items-center py-1">
              <%= link_to new_user_registration_path, class: 'mr-8 flex items-center gap-2' do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
                </svg>
                <span class="my-auto ml-2 normal-case">Register to App</span>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_top_header.html.erb
<!-- Load Tailwind Play CDN-->
<%= javascript_include_tag 'https://cdn.tailwindcss.com' %>
<script>
tailwind.config = {
    theme: {
      extend: {
        colors: {
          clifford: '#eecccc'
        },
        keyframes: {
          wiggle: {
            '0%, 100%': { transform: 'rotate(-10deg)' },
            '50%': { transform: 'rotate(10deg)' }
          }
        },
        animation: {
          wiggle: 'wiggle .5s ease-in-out infinite'
        }
      }
    }
  }
</script>

<!-- Load Material Tailwind from Creative Tim-->
<!-- stylesheet -->
<%= stylesheet_link_tag "https://unpkg.com/@material-tailwind/html@latest/styles/material-tailwind.css" %>
<!-- script -->
<%= javascript_include_tag 'https://unpkg.com/@material-tailwind/html@latest/scripts/script-name.js' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%# javascript_importmap_tags %>

    <%# render "layouts/top_header" %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% elsif alert.present? %>
      <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></p>
    <% end %>
    
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= render "layouts/bottom_header" %>
  </body>
</html>